# Generated by Django 6.1 on 2026-10-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_result_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
