# Generated by Django 6.1 on 2026-10-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0005_remove_result_unique_result_per_assessment_enrollment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="expected_qr_page_labels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessment",
            name="qr_test",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
