# Generated by Django 6.1 on 2026-10-06 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_assessment_expected_qr_page_labels_and_more"),
        ("courses", "0004_alter_course_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="courses.course",
            ),
        ),
    ]
