from django.urls import path

from submissions.views import (
    RecognitionMethodsView,
    ScriptPageFileView,
    ScriptPageReviewView,
    ScriptUploadFileView,
    SubmissionCorrectionView,
    SubmissionDetailView,
    SubmissionFileDownloadView,
    SubmissionHistoryFileView,
    SubmissionHistoryView,
    SubmissionListCreateView,
    SubmissionRecognitionImageView,
    SubmissionRetryRecognitionView,
    SubmissionRevisionFileView,
    SubmissionVerificationQueueView,
    SubmissionVerifyView,
)

urlpatterns = [
    path("history/", SubmissionHistoryView.as_view(), name="submission-history"),
    path(
        "<int:pk>/history-file/",
        SubmissionHistoryFileView.as_view(),
        name="submission-history-file",
    ),
    path(
        "<int:pk>/revisions/<int:revision_id>/file/",
        SubmissionRevisionFileView.as_view(),
        name="submission-revision-file",
    ),
    path(
        "<int:pk>/uploads/<int:upload_id>/file/",
        ScriptUploadFileView.as_view(),
        name="submission-upload-file",
    ),
    path(
        "<int:pk>/pages/<int:page_id>/review/",
        ScriptPageReviewView.as_view(),
        name="submission-page-review",
    ),
    path(
        "<int:pk>/pages/<int:page_id>/file/",
        ScriptPageFileView.as_view(),
        name="submission-page-file",
    ),
    path(
        "recognition-methods/",
        RecognitionMethodsView.as_view(),
        name="recognition-methods",
    ),
    path(
        "",
        SubmissionListCreateView.as_view(),
        name="submission-list-create",
    ),
    path(
        "verification-queue/",
        SubmissionVerificationQueueView.as_view(),
        name="submission-verification-queue",
    ),
    path(
        "<int:pk>/",
        SubmissionDetailView.as_view(),
        name="submission-detail",
    ),
    path(
        "<int:pk>/correct/",
        SubmissionCorrectionView.as_view(),
        name="submission-correct",
    ),
    path(
        "<int:pk>/verify/",
        SubmissionVerifyView.as_view(),
        name="submission-verify",
    ),
    path(
        "<int:pk>/file/",
        SubmissionFileDownloadView.as_view(),
        name="submission-file-download",
    ),
    path(
        "<int:pk>/recognition-image/",
        SubmissionRecognitionImageView.as_view(),
        name="submission-recognition-image",
    ),
    path(
        "<int:pk>/retry-recognition/",
        SubmissionRetryRecognitionView.as_view(),
        name="submission-retry-recognition",
    ),
]
