# Generated by Django 6.1 on 2026-08-09 16:06

from django.db import migrations

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
