# Generated by Django 6.1 on 2026-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('LECTURER', 'Lecturer'), ('MARKER', 'Marker')], default='LECTURER', max_length=20),
        ),
    ]
