# Generated by Django 6.1 on 2026-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthThrottleCache",
            fields=[
                (
                    "cache_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("expires", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "auth_throttle_cache",
            },
        ),
    ]
