# Generated by Django 6.1 on 2026-09-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_enrollment'),
        ('submissions', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ocr', 'OCR'), ('bubble', 'Bubble')], max_length=20)),
                ('outcome', models.CharField(choices=[('matched', 'Matched'), ('no_match', 'No match'), ('no_candidate', 'No candidate'), ('region_not_found', 'Region not found'), ('error', 'Error')], max_length=20)),
                ('processing_version', models.CharField(max_length=50)),
                ('raw_text', models.TextField(blank=True)),
                ('raw_candidate', models.CharField(blank=True, max_length=50)),
                ('suggested_student_number', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('confidence_type', models.CharField(choices=[('none', 'None'), ('ocr_score', 'OCR score'), ('bubble_margin', 'Bubble margin')], default='none', max_length=20)),
                ('column_ambiguity', models.JSONField(blank=True, default=list)),
                ('region', models.JSONField(blank=True, null=True)),
                ('region_image', models.FileField(blank=True, upload_to='recognition/%Y/%m/%d/')),
                ('quality_issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_attempts', to='submissions.submission')),
                ('suggested_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', '-created_at'], name='recognition_latest_idx')],
            },
        ),
    ]
