# Generated by Django 6.1 on 2026-09-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_enrollment'),
        ('submissions', '0003_alter_submission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('matched', 'Matched'), ('needs_verification', 'Needs verification'), ('verified', 'Verified'), ('marked', 'Marked')], help_text='Null on creation.', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('matched', 'Matched'), ('needs_verification', 'Needs verification'), ('verified', 'Verified'), ('marked', 'Marked')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional explanation for manual corrections.')),
                ('actor', models.ForeignKey(blank=True, help_text='User who made the change. Null for system-initiated changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_audits', to=settings.AUTH_USER_MODEL)),
                ('new_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.enrollment')),
                ('previous_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.enrollment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='submissions.submission')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['submission', '-timestamp'], name='submissions_submiss_76c2e6_idx')],
            },
        ),
    ]
