# Generated by Django 6.1 on 2026-09-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_max_mark_result'),
        ('students', '0003_enrollment'),
        ('submissions', '0004_submission_audit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['uploaded', 'matched', 'needs_verification', 'verified', 'marked'])), name='submission_status_valid'),
        ),
    ]
