# Generated by Django 6.1 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_submission_status_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
