# Generated by Django 6.1 on 2026-09-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_recognitionattempt'),
        ('submissions', '0005_submission_status_constraint'),
    ]

    operations = [
    ]
