# Generated by Django 6.1 on 2026-09-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_submission_status_recognitionjob'),
        ('submissions', '0008_recognitionattempt_error_and_candidates'),
    ]

    operations = [
    ]
