# Generated by Django 6.1 on 2026-09-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_version'),
        ('submissions', '0010_extend_submission_status_constraint'),
    ]

    operations = [
    ]
