# Generated by Django 6.1 on 2026-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0011_merge_20260929_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognitionattempt",
            name="column_scores",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recognitionattempt",
            name="template_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="submission",
            name="recognition_method",
            field=models.CharField(
                choices=[
                    ("ocr", "Handwritten digits (OCR)"),
                    ("bubble", "Filled bubbles"),
                ],
                default="ocr",
                max_length=20,
            ),
        ),
    ]
