# Generated by Django 6.1 on 2026-10-06 17:36

from django.db import migrations, models


def retire_marked_status(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    Submission.objects.filter(status="marked", enrollment__isnull=False).update(
        status="verified"
    )
    Submission.objects.filter(status="marked", enrollment__isnull=True).update(
        status="needs_verification"
    )
    # Preserve the actor, time and enrollment of each historical event.
    Audit = apps.get_model("submissions", "SubmissionAudit")
    Audit.objects.filter(previous_status="marked").update(previous_status="verified")
    Audit.objects.filter(new_status="marked").update(new_status="verified")


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0005_remove_result_unique_result_per_assessment_enrollment_and_more",
        ),
        ("students", "0003_enrollment"),
        ("submissions", "0012_bubble_recognition_method_and_evidence"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="submission",
            name="submission_status_valid",
        ),
        migrations.RunPython(retire_marked_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("matched", "Matched"),
                    ("needs_verification", "Needs verification"),
                    ("verified", "Verified"),
                    ("processing", "Processing"),
                    ("recognition_failed", "Recognition failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submissionaudit",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("matched", "Matched"),
                    ("needs_verification", "Needs verification"),
                    ("verified", "Verified"),
                    ("processing", "Processing"),
                    ("recognition_failed", "Recognition failed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submissionaudit",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("uploaded", "Uploaded"),
                    ("matched", "Matched"),
                    ("needs_verification", "Needs verification"),
                    ("verified", "Verified"),
                    ("processing", "Processing"),
                    ("recognition_failed", "Recognition failed"),
                ],
                help_text="Null on creation.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "uploaded",
                            "matched",
                            "needs_verification",
                            "verified",
                            "processing",
                            "recognition_failed",
                        ],
                    )
                ),
                name="submission_status_valid",
            ),
        ),
    ]
