# Generated by Django 6.1 on 2026-10-06 20:20

from django.db import migrations, models


def backfill_identity(apps, schema_editor):
    Audit = apps.get_model("submissions", "SubmissionAudit")

    def identity(enrollment):
        if enrollment is None:
            return {}
        return {
            "origin": "migration_current_reference",
            "enrollment_id": enrollment.pk,
            "student_id": enrollment.student_id,
            "student_number": enrollment.student.student_number,
            "course_id": enrollment.course_id,
        }

    batch = []
    for audit in (
        Audit.objects.using(schema_editor.connection.alias)
        .select_related("previous_enrollment__student", "new_enrollment__student")
        .iterator(chunk_size=500)
    ):
        audit.previous_identity = identity(audit.previous_enrollment)
        audit.new_identity = identity(audit.new_enrollment)
        batch.append(audit)
        if len(batch) == 500:
            Audit.objects.using(schema_editor.connection.alias).bulk_update(
                batch, ["previous_identity", "new_identity"]
            )
            batch = []
    if batch:
        Audit.objects.using(schema_editor.connection.alias).bulk_update(
            batch, ["previous_identity", "new_identity"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0013_remove_submission_submission_status_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionaudit",
            name="new_identity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="submissionaudit",
            name="previous_identity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_identity, migrations.RunPython.noop),
    ]
