# Generated by Django 6.1 on 2026-10-06 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_assessment_expected_qr_page_labels_and_more"),
        ("students", "0003_enrollment"),
        ("submissions", "0014_submissionaudit_new_identity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="script-pages/%Y/%m/%d/")),
                ("source_page", models.PositiveIntegerField()),
                ("source_filename", models.CharField(max_length=255)),
                ("qr_fields", models.JSONField(blank=True, default=dict)),
                ("qr_status", models.CharField(max_length=32)),
                ("page_label", models.CharField(blank=True, max_length=20)),
                ("excluded", models.BooleanField(default=False)),
                ("review_history", models.JSONField(blank=True, default=list)),
                ("recognition_outcome", models.CharField(blank=True, max_length=40)),
                ("quality_issues", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ScriptUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="script-uploads/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="submission",
            name="qr_group_key",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="submission",
            name="qr_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="submission",
            name="qr_review_issues",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("qr_group_key", ""), _negated=True),
                fields=("assessment", "qr_group_key"),
                name="unique_assessment_qr_group",
            ),
        ),
        migrations.AddField(
            model_name="scriptpage",
            name="linked_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="script_pages",
                to="students.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="scriptpage",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="submissions.submission",
            ),
        ),
        migrations.AddField(
            model_name="scriptpage",
            name="suggested_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="scriptupload",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="script_uploads",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="scriptpage",
            name="upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="submissions.scriptupload",
            ),
        ),
    ]
