# Generated by Django 6.1 on 2026-10-06 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def select_latest_verified(apps, schema_editor):
    from django.db.models import OuterRef, Subquery
    from django.utils import timezone

    Submission = apps.get_model("submissions", "Submission")
    Audit = apps.get_model("submissions", "SubmissionAudit")
    Revision = apps.get_model("submissions", "SubmissionFileRevision")
    Email = apps.get_model("distribution", "ScriptEmail")
    Job = apps.get_model("submissions", "RecognitionJob")
    db = schema_editor.connection.alias
    verified_identity = (
        Audit.objects.using(db)
        .filter(
            submission_id=OuterRef("pk"),
            new_status="verified",
            new_enrollment_id=OuterRef("enrollment_id"),
        )
        .order_by("-timestamp", "-pk")
        .values("new_identity")[:1]
    )
    rows = (
        Submission.objects.using(db)
        .exclude(file="")
        .select_related("enrollment__student")
        .annotate(verified_identity=Subquery(verified_identity))
        .order_by("pk")
    )
    batch = []
    for row in rows.iterator(chunk_size=500):
        identity = {}
        if row.enrollment_id:
            student = row.enrollment.student
            identity = {
                "origin": "migration_current_reference",
                "student_number": student.student_number,
                "first_name": student.first_name,
                "last_name": student.last_name,
            }
            if row.verified_identity and row.verified_identity.get("student_number"):
                identity["student_number"] = row.verified_identity["student_number"]
                identity["origin"] = "migration_verified_audit"
                identity["name_origin"] = "migration_current_reference"
        batch.append(
            Revision(
                submission_id=row.pk,
                file=row.file.name,
                version=row.version,
                status=row.status,
                original_filename=row.original_filename,
                student_identity=identity,
            )
        )
        if len(batch) == 500:
            Revision.objects.using(db).bulk_create(batch)
            batch = []
    if batch:
        Revision.objects.using(db).bulk_create(batch)
    previous_key, winner = None, None
    rows = (
        Submission.objects.using(db)
        .filter(status="verified", enrollment__isnull=False)
        .select_related("enrollment__student")
        .order_by("assessment_id", "enrollment_id", "-created_at", "-pk")
    )
    for row in rows.iterator(chunk_size=500):
        key = (row.assessment_id, row.enrollment_id)
        if key != previous_key:
            previous_key, winner = key, row.pk
        elif row.pk != winner:
            Submission.objects.using(db).filter(pk=row.pk).update(
                superseded_at=timezone.now(),
                superseded_by_id=winner,
                version=row.version + 1,
            )
            Email.objects.using(db).filter(
                submission_id=row.pk,
                status__in=["queued", "awaiting_approval", "failed"],
            ).update(status="superseded", lease_expires_at=None)
            Job.objects.using(db).filter(
                submission_id=row.pk, status__in=["queued", "running"]
            ).update(
                status="cancelled", lease_expires_at=None, finished_at=timezone.now()
            )
            snapshot = {
                "origin": "migration_current_reference",
                "enrollment_id": row.enrollment_id,
                "student_id": row.enrollment.student_id,
                "student_number": row.enrollment.student.student_number,
                "course_id": row.enrollment.course_id,
            }
            Audit.objects.using(db).create(
                submission_id=row.pk,
                previous_status="verified",
                new_status="verified",
                previous_enrollment_id=row.enrollment_id,
                new_enrollment_id=row.enrollment_id,
                previous_identity=snapshot,
                new_identity=snapshot,
                reason="Legacy duplicate retained; newer verified script selected as current",
            )
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0002_script_email"),
        ("assessments", "0007_alter_assessment_course"),
        ("students", "0004_enrollment_version_enrollment_withdrawal_reason_and_more"),
        (
            "submissions",
            "0015_scriptpage_scriptupload_submission_qr_group_key_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionFileRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="retained-script-revisions/")),
                ("status", models.CharField(max_length=20)),
                ("version", models.PositiveIntegerField()),
                ("original_filename", models.CharField(max_length=255)),
                ("student_identity", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version", "-pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="submission",
            name="unique_assessment_qr_group",
        ),
        migrations.AddField(
            model_name="submission",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_scripts",
                to="submissions.submission",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="assessments.assessment",
            ),
        ),
        migrations.AlterField(
            model_name="submissionaudit",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_entries",
                to="submissions.submission",
            ),
        ),
        migrations.AlterField(
            model_name="submissionaudit",
            name="actor",
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
                related_name="submission_audits",
                help_text="User who made the change. Null for system-initiated changes.",
            ),
        ),
        migrations.AddField(
            model_name="submissionfilerevision",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_revisions",
                to="submissions.submission",
            ),
        ),
        migrations.RunPython(select_latest_verified, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True),
                    ("enrollment__isnull", False),
                    ("status", "verified"),
                    ("superseded_at__isnull", True),
                ),
                fields=("assessment", "enrollment"),
                name="one_current_verified_script",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("qr_group_key", ""), _negated=True),
                    ("archived_at__isnull", True),
                    ("superseded_at__isnull", True),
                ),
                fields=("assessment", "qr_group_key"),
                name="unique_assessment_qr_group",
            ),
        ),
    ]
